import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {  Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AURA Digital Labs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">  
      <Head>
        <link rel="icon" href="/Aura Logo-02.png" />
      </Head>  
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <NavBar />
        <Theme accentColor="crimson" grayColor="sand" radius="large" scaling="95%">
        {children}
        </Theme>  
      </body>
    
    </html>
  );
}
